### ISSUE TITLE
Installation log

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/msi-installer#12] opened 2022-10-28 16:14 UTC
When installing from the command line (with the command below) it would be nice to see some output of the installation on the window you triggered it or leave the last one open pending a user "enter" or something to see some output. 

```
msiexec.exe /i netdata.msi TOKEN=jyx4ymCG5goYv96cG4cZuMx9kT371_bIj8nmqW-HCN267fVfT8no8geHnq30H4SumIhQrDiwCrc5-iJrSj31SLmTV3fNxrJJ1gZMBmjAhCvLNslYtetAsj6zleaKXBvHRH_ofSc URL=https://app.netdata.cloud/
```

**Comment by cakrit** [comment] 2022-10-31 19:27
Please update here and document in the README when the logging output file is there.

**Comment by cakrit** [comment] 2022-11-03 16:28
@dfpr reminder that we still need the logfile. Installer didn't work and I don't know why.

**Comment by dfpr** [comment] 2022-11-03 16:48
@cakrit I'm working on this right now, I'll finish soon

**Comment by cakrit** [comment] 2022-11-03 17:15
noob question, isn't it possible to add our log (debug) messages to the output of 
`msiexec /i netdata.msi /L*vx "C:\folder\ExampleLogFilename.txt"`

**Comment by cakrit** [comment] 2022-11-03 17:16
I mean, instead of doing our own thing...

**Comment by dfpr** [comment] 2022-11-03 17:34
> noob question, isn't it possible to add our log (debug) messages to the output of 
> 
> `msiexec /i netdata.msi /L*vx "C:\folder\ExampleLogFilename.txt"`

Usual msi logs include file operations and return codes of actions, output for scripts won't appear there so there's a need for saving a log file outside Windows Installer.

**Comment by cakrit** [comment] 2022-11-03 17:36
Ok, thanks.

**Comment by dfpr** [comment] 2022-11-03 20:48
Installation log now saved to c:\netdata.log, README has been updated.

**Comment by cakrit** [comment] 2022-11-04 13:29
I see garbage in netdata.log. The following is from notepad++, MS Word doesn't know what to do with it.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/43294513/199983986-a1292bc5-8e22-414f-a59f-5fefcffac836.png">

**Comment by dfpr** [comment] 2022-11-04 13:32
> I see garbage in netdata.log. The following is from notepad++, MS Word doesn't know what to do with it.
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/43294513/199983986-a1292bc5-8e22-414f-a59f-5fefcffac836.png">

Might be that wsl.exe outputs double byte characters when ansi is expected. Send me the log please.

**Comment by cakrit** [comment] 2022-11-04 13:40
Here it is cleaned up (installation failed): [netdata.log](https://github.com/netdata/msi-installer/files/9938712/netdata.log)

Here is the original: [netdata.log](https://github.com/netdata/msi-installer/files/9938716/netdata.log)

I see that Wordpad is able to open both, actually, those nulls (\x00) show up as extra spaces.

**Comment by dfpr** [comment] 2022-11-04 13:51
wsl.exe is outputting unicode, check https://github.com/microsoft/WSL/issues/4607 .The fix shown there didn't work for me thou. For now the null character can be removed for readability. I'll work on the installation failed issue first before fixing this.

**Comment by cakrit** [comment] 2022-11-07 16:17
As mentioned in #10 the log also includes some errors that aren't really errors.

**Comment by dfpr** [comment] 2022-11-10 20:35
I've improved the log file to show the least of errors, what might remain are faux error messages unrelated to the installation and caused by incorrect return codes plus unexpected unicode output from wsl.exe

**Comment by cakrit** [comment] 2022-11-21 16:34
Are the following "faux error messages"? Any suggestions on how to get rid of them?

```
SUCCESS: Specified value was saved.
ADDING SCRIPTS TO PATH
cmd.exe : ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).
At C:\Netdata\install.ps1:166 char:2
+     cmd.exe /c setx /m PATH "%PATH%;C:\Netdata"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Invalid ...an '2' time(s).:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Type "SETX /?" for usage.
STARTING AGENT
cmd.exe : 2022-11-21 14:39:54: netdata INFO  : MAIN : CONFIG: cannot load cloud config 
'/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
At C:\Netdata\install.ps1:193 char:1
+ cmd.exe /c wsl -d netdata netdata
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (2022-11-21 14:3...ernal defaults.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by cakrit** [comment] 2022-11-23 13:55
Yesterday's build had the following:
```
ADDING SCRIPTS TO PATH
cmd.exe : ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).
At C:\Netdata\install.ps1:167 char:2
+     cmd.exe /c setx /m PATH "%PATH%;C:\Netdata" | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Invalid ...an '2' time(s).:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Type "SETX /?" for usage.
```

**Comment by dfpr** [comment] 2022-11-23 14:09
I need the full  log

**Comment by dfpr** [comment] 2022-11-29 02:34
Path is added now through Windows Installer, uninstaller can fix old leftover entries.

**Comment by cakrit** [comment] 2022-11-30 16:46
I'm closing this and will create a new one if I see any new weird things.

**Closed by cakrit** 2022-11-30 16:46 UTC
Labels: enhancement
